config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'posts#index'

  devise_for :users, controllers: {:omniauth_callbacks => "users/omniauth_callbacks"}

  get '/users/:id', to: 'users#show', as: :user
  get '/links/new', to: 'posts#links'

  resources :posts do
  	resources :comments
  	member do 
  		put :upvote, to: 'posts#upvote'
  		put :downvote, to: 'posts#downvote'
  	end
  end

  resources :comments do
  	resources :comments
  	member do
  		put :upvote, to: 'comments#upvote'
  		put :downvote, to: 'comments#downvote'
  	end
  end

  namespace :admin do
  	resources :posts
  	resources :comments
  end

  resources :conversations do
  	resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :commentable, polymorphic: true
	has_many :comments, :as => :commentable
	validates :body, :presence =>  true
	acts_as_votable

	def karma
		upvotes = self.get_upvotes.size
		downvotes = self.get_downvotes.size
		karma = upvotes - downvotes
		karma
	end
	
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments, :as => :commentable
	validates :title, :presence => true
	acts_as_votable

	def comment_total
		parent_comments = Comment.where(:commentable_id => id)
		child_comments = Comment.where(:commentable_id => parent_comments.map(&:id))
		child_comments
	end

	def karma
		upvotes = self.get_upvotes.size
		downvotes = self.get_downvotes.size
		karma = upvotes - downvotes
		karma
	end
	
end

app/models/received_message.rb
class ReceivedMessage < ApplicationRecord
end

app/models/sent_message.rb
class SentMessage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :omniauthable, :omniauth_providers => [:twitter]
  has_many :posts
  has_many :comments, through: :posts
  has_many :votes, through: :posts
  has_many :votes, through: :comments
  validates :email, presence: true, uniqueness:true
  validates :username, presence: true, uniqueness: true
  acts_as_voter

  def self.from_omniauth(auth)
  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user| 
  		user.username = auth.info.nickname
  		user.email = auth.info.email
  		user.password = Devise.friendly_token[0,20]
  	end
  end

  def self.new_with_session(params, session)
  	super.tap do |user|
  		if data = session["devise.twitter_data"] && session["devise.twitter_data"].except("extra")
  			user.username = data["nickname"] if user.username.blank?
  			user.email = data["email"] if user.email.blank?
  		end
  	end
  end

  def post_upvotes 
    upvotes = []
    self.posts.each do |post|
      upvotes << post.get_upvotes.size 
    end
    upvotes.sum
  end

  def post_downvotes
    downvotes = []
    self.posts.each do |post|
      downvotes << post.get_downvotes.size
    end
    downvotes.sum
  end

  def comment_upvotes
    upvotes = []
    self.comments.each do |comment|
      upvotes << comment.get_upvotes.size
    end
    upvotes.sum
  end

  def comment_downvotes
    downvotes = []
    self.comments.each do |comment|
      downvotes << comment.get_downvotes.size
    end
    downvotes.sum
  end

  def post_karma
    self.post_upvotes - self.post_downvotes
  end

  def comment_karma
    self.comment_upvotes - self.comment_downvotes
  end

  def content
    content = self.posts + self.comments
    content
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!, :find_commentable, :set_user

	def new
		@comment = Comment.new
	end

	def create
		@comment = @commentable.comments.new(comment_params)
		@comment.user_id = @user.id
		@comment.post_id = params[:post_id]
		if @comment.save
			redirect_back fallback_location: root_path
		else
			redirect_back fallback_location: root_path
		end
	end

	def edit
		@comment = Comment.find(params[:id])
	end

	def update
		@comment = Comment.find(params[:id])
		@comment.update
		redirect_back fallback_location: root_path
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_back fallback_location: root_path
	end

	def upvote
		comment = Comment.find(params[:id])
		comment.upvote_by(current_user)
		redirect_back fallback_location: root_path
	end

	def downvote
		comment = Comment.find(params[:id])
		comment.downvote_by(current_user)
		redirect_back fallback_location: root_path
	end

	private

	def comment_params
		params.require(:comment).permit(:body, :user_id, :post_id)
	end

	def set_user
		@user = current_user
	end

	def find_commentable
		@commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
		@commentable = Post.find_by_id(params[:post_id]) if params[:post_id]
	end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!

	def index
		@posts = Post.all
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Post created"
			redirect_to post_path(@post)
		else
			flash[:failure] = "Post failed to create"
			redirect_to new_post_path
		end
	end

	def links
		@post = current_user.posts.build
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		@post.update(post_params)
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to root_path
	end

	def upvote
		@post = Post.find(params[:id])
		@post.upvote_by(current_user)
		redirect_back fallback_location: root_path
	end

	def downvote
		@post = Post.find(params[:id])
		@post.downvote_by(current_user)
		redirect_back fallback_location: root_path
	end

	private


	def post_params
		params.require(:post).permit(:title, :body, :url, :user_id)
	end

end

app/controllers/received_messages_controller.rb
class ReceivedMessagesController < ApplicationController
end

app/controllers/sent_messages_controller.rb
class SentMessagesController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

	def twitter
		@user = User.from_omniauth(request.env["omniauth.auth"])

		if @user.persisted?
			sign_in_and_redirect @user
			set_flash_message(:notice, :success, :kind => "Twitter")
		else
			session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
			redirect_to new_user_registration_url
		end
	end

	def failure
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
		render "users/profile"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/received_messages_helper.rb
module ReceivedMessagesHelper
end

app/helpers/sent_messages_helper.rb
module SentMessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<li>
	<%= comment.body %> -
	<small><%= comment.karma %> points by <%= link_to comment.user.username, user_path(comment.user) %> <%= time_ago_in_words(comment.created_at) %> ago</small>

	<small><%= link_to "upvote", upvote_comment_path(comment), method: :put %></small>
	<small><%= link_to "downvote", downvote_comment_path(comment), method: :put	%></small>

	<%= form_for [comment, Comment.new] do |f| %>
	<%= f.text_area :body, placeholder: "Reply to this comment" %>
	<br>
	<% f.hidden_field :user_id %>
	<% f.hidden_field :post_id %>
	<% f.hidden_field :commentable_id %>
	<%= f.submit "Submit reply" %>
	<% end %>

	<ul>
		<%= render(partial: 'comments/comment', collection: comment.comments) %>
	</ul>

</li>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

<h3>Title</h3>

<fieldset>
	<%= f.text_field :title %>
</fieldset>

<h3>URL</h3>

<fieldset>
	<%= f.text_field :url %>
</fieldset>

<br>
<textarea class="form-control" rows="3"<%= f.text_area :body %> 
</textarea>
<br><br>

<div class = "actions">
	<%=	f.submit %>
</div>

<br>

<% end %>

app/views/posts/_link.html.erb
<%= form_for(@post) do |f| %>

<h3>Title</h3>

<fieldset>
	<%= f.text_field :title %>
</fieldset>

<br>

<h3>URL</h3>
<fieldset>
	<%= f.text_field :url %>
</fieldset>

<br><br>


	<%=	f.submit %>


<br>

<% end %>

app/views/posts/index.html.erb
<a href="links/new"><button type="button" class="btn btn-primary btn-lg">submit a link</button></a>
<a href="posts/new"><button type="button" class="btn btn-primary btn-lg">submit a post</button></a>

<% @posts.each_with_index do |post, i| %>
<% if !post.url.blank? %>
<h3><%=	"#{i+1}. "%><%= link_to post.title, post.url %></h3>
<% else %>
<h3><%=	"#{i+1}. "%><%= link_to post.title, post_path(post) %></h3>
<% end %>
<small><%= post.karma %> points by <%= link_to post.user.username, user_path(post.user) %> <%= time_ago_in_words(post.created_at) %> ago</small>
<small><%= link_to "upvote ", upvote_post_path(post), method: :put %></small>
<small><%= link_to "downvote ", downvote_post_path(post), method: :put %></small>
<%= link_to "#{post.comment_total.size} comments", post_path(post) %>
<% end %>

app/views/posts/links.html.erb
<%= render 'link', post: @post %>

<%= link_to "Back", root_path %>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

<%= link_to "Back", root_path %>

app/views/posts/show.html.erb
<% if !@post.url.blank? %>
<h3><fieldset><%= link_to @post.title, @post.url, target: "_blank" %></fieldset></h3>
<% else %>
<fieldset><%= @post.title %></fieldset>
<% end %>

<fieldset>
	<%= @post.body %>
</fieldset>

<small><%= @post.karma %> points by <%= link_to @post.user.username, user_path(@post.user) %> <%= time_ago_in_words(@post.created_at) %> ago</small>

<small><%= link_to "upvote ", upvote_post_path(@post), method: :put %></small>
<small><%= link_to "downvote ", downvote_post_path(@post), method: :put %></small>

<% if @post.user_id == current_user.id %>
<small><%= link_to "edit post", edit_post_path(@post) %></small>
<% end %>

<br><br>


<h3>all <%= @post.comment_total.size %> comments</h3>

<%= form_for [@post, Comment.new] do |f| %>
<textarea class="form-control" rows="3" placeholder="add a comment"
<%= f.text_area :body %>
</textarea>
<br>
<%= f.submit "Submit comment" %>
<% end %>

<div class="container">

	<ul>
		<%= render(partial: 'comments/comment', collection: @post.comments) %>
	</ul>

</div>

app/views/users/profile.html.erb
<h3><%= @user.username %></h3>

<h3>post karma: <%= @user.post_karma %></h3>

<h3>comment karma: <%= @user.comment_karma %></h3>

<br>